sonar.projectKey=kyuhisan_learnsmart_frontend
sonar.organization=kyuhisan

sonar.exclusions=\
  node_modules/**,\
  dist/**,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  src/**/*mockData*,\
  src/styles/tokens.ts
