spring.application.name=learnSmart

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

gemini.api.key=${GEMINI_API_KEY}
open.api.key=${OPENAI_API_KEY}
google.tts.api.key=${GOOGLE_TTS_API_KEY}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_URI}
server.port=${PORT:8081}
